### ISSUE TITLE
Some questions about build a bio-site project

### ISSUE THREAD

**Issue by tzayuan** [GeeLaw/bio-site#1]
Hi @GeeLaw, 

The bio-site you have developed and maintained is very beautiful and useful!

On this basis, I had the idea to develop a set of this system myself. I don't seem to have a hierarchical understanding of the way your project is organized after reading it, I think it's because I lack knowledge in certain areas. I currently have the foundation of HTML, CSS and JavaScript, but I still can't imagine how to create such a system template, and can only think of static page construction, but can't encapsulate the page into a system that allows page management through foolproof operation.

What additional knowledge/content do I need to catch up on in order to reach my idea?

Thanks! (Also, amazing to see that you are involved in a work about medical image registration, which is what I currently do, fantastic karma.

Best Regards,
Tzayuan

**Comment by GeeLaw** [comment]
Thank you for your compliment.

The question is our of the scope of this repository, but I'm putting down a response. As you might have realized, the heavy lift is done by external libraries (KaTeX and Marked), with some customizations, which you may inspect by comparing files in this repository with those from their original repositories. I know little specifics of JavaScript or CSS or HTML. I wrote them as I read docs and tutorials here and there (MDN and other results from search engine).

I no longer work on medical image registration.
